version: '3.3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    image: adrianowead/viware-base-php
    container_name: viware-base-php
    hostname: viware-base-php
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/html'
